name: pdsm
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - aom=3.9.1=he0c23c2_0
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.11.12=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - dav1d=1.2.1=hcfcfb64_0
  - expat=2.7.3=h9214b88_0
  - ffmpeg=7.1.0=gpl_h2585aa8_705
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=h57928b3_0
  - fribidi=1.0.16=hfd05255_0
  - gdk-pixbuf=2.42.12=hab781ea_1
  - graphite2=1.3.14=hac47afa_2
  - harfbuzz=11.4.5=h5f2951f_0
  - icu=75.1=he0c23c2_0
  - lerc=4.0.0=h6470a55_1
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.4.4=hd77b12b_1
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libglib=2.84.4=hfaec014_0
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.2=hfd05255_0
  - libopus=1.5.2=h2466b09_0
  - libpng=1.6.51=h7351971_0
  - librsvg=2.58.4=h5ce5fed_3
  - libtiff=4.7.0=hfc51747_1
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h02ab6af_0
  - openh264=2.5.0=ha9db3cd_0
  - openssl=3.6.0=h725018a_0
  - pango=1.56.4=h03d888a_0
  - pcre2=10.46=h3402e2f_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h5112557_1
  - python=3.12.12=h716150d_1
  - sqlite=3.51.0=hda9a48d_0
  - svt-av1=2.3.0=he0c23c2_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py312haa95532_0
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h1b5488d_4
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - antlr4-python3-runtime==4.9.3
      - apprise==1.9.6
      - asteroid-filterbanks==0.4.0
      - attrs==25.4.0
      - audioread==3.1.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - ci-sdr==0.0.2
      - click==8.3.1
      - colorama==0.4.6
      - configargparse==1.7.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - decorator==5.2.1
      - distance==0.1.3
      - editdistance==0.8.1
      - einops==0.8.1
      - espnet==202511
      - espnet-tts-frontend==0.0.3
      - fast-bss-eval==0.1.3
      - filelock==3.20.0
      - fonttools==4.61.0
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - g2p-en==2.1.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - idna==3.11
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==4.13.0
      - inflect==7.5.0
      - jaconv==0.4.1
      - jamo==0.4.1
      - jinja2==3.1.6
      - joblib==1.5.2
      - kaldiio==2.18.1
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - librosa==0.11.0
      - lightning==2.6.0
      - lightning-utilities==0.15.2
      - llvmlite==0.45.1
      - markdown==3.10
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - more-itertools==10.8.0
      - moviepy==2.2.1
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - networkx==3.6
      - nltk==3.9.2
      - numba==0.62.1
      - numpy==2.2.6
      - oauthlib==3.3.1
      - omegaconf==2.3.0
      - opencv-python==4.12.0.88
      - opt-einsum==3.4.0
      - packaging==25.0
      - pillow==11.3.0
      - platformdirs==4.5.1
      - pooch==1.8.2
      - ppgs==0.0.9
      - proglog==0.1.12
      - propcache==0.4.1
      - protobuf==6.33.2
      - psutil==7.1.3
      - pycparser==2.23
      - pypar==0.0.6
      - pyparsing==3.2.5
      - pypinyin==0.44.0
      - pyreadline3==3.5.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytorch-lightning==2.6.0
      - pyworld==0.3.5
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - sentencepiece==0.2.0
      - setuptools==73.0.1
      - six==1.17.0
      - soundfile==0.13.1
      - soxr==1.0.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.9.1
      - torch-complex==0.4.4
      - torchaudio==2.9.1
      - torchmetrics==1.8.2
      - torchutil==0.1.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - typeguard==4.4.4
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - unidecode==1.4.0
      - urllib3==2.6.0
      - werkzeug==3.1.4
      - yapecs==0.4.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: C:\Users\hhenn\anaconda3\envs\pdsm
